Build scraper for Glovo
invisible-tech/ace-glovo-scraper pull request #2
Opened 2022-10-11 07:37 UTC by omobolaji-codes

2022-10-11 19:31 UTC, SarthakC requested changes
You can do better!

2022-10-11 19:31 UTC, SarthakC commented on app.py
> +    url = "https://glovoapp.com/ge/en/batumi/batumi-pizza-batumi/"
Why are we hardcoding the URL?
It should be a body parameter.

2022-10-11 19:31 UTC, SarthakC commented on app.py
> +    return {}
We should not be returning an empty object. We should return 
`{"message":"Restaurant not found"}` if the restaurant doesn't exist. Along with a status code `404`.

OR

`{"message": "An error has occurred"}` if there is another error code. Along with a status code `500`.

2022-10-11 19:31 UTC, SarthakC commented on src/glovo_scraper.py
> +def get_requests(url: str) -> BeautifulSoup:
The function is named `get_requests` but returns a `soup` object.
We can name it `get_soup_from_url`.

2022-10-11 19:31 UTC, SarthakC commented on src/glovo_scraper.py
> +    response = requests.get(url, timeout=60)
We should use a `Session` object for efficient scraping.
And inject the `session` variable as a dependency for this function.

2022-10-11 19:31 UTC, SarthakC commented on src/glovo_scraper.py
> +    script_content = str(soup.find("body").find_all("script")[1].string)  # type: ignore
Why are we ignoring type here?

2022-10-11 19:31 UTC, SarthakC commented on src/glovo_scraper.py
> +def process_automation(url: str) -> dict[str, Optional[str]]:
`process_automation` this names tells us nothing about the function.

2022-10-11 19:31 UTC, SarthakC commented on src/glovo_scraper.py
> +    process_automation("https://glovoapp.com/ge/en/batumi/batumi-pizza-batumi/")
Why are we invoking the function here?

2022-10-11 19:31 UTC, SarthakC commented on src/glovo_scraper.py
> +        "Phone Number": phone_number,
key names should be `camelCase`

2022-10-11 19:31 UTC, SarthakC commented on src/utils/autolysis.py
> +    return str(json.loads(resp)["id"])
Have we started with the autolysis integration yet?
If not, then we should not commit this code yet.

2022-10-11 19:31 UTC, SarthakC commented on src/glovo_scraper.py
> +load_dotenv()
This should only be invoked in the `app.py` file.

2022-10-11 19:41 UTC, omobolaji-codes commented on src/glovo_scraper.py
> +    process_automation("https://glovoapp.com/ge/en/batumi/batumi-pizza-batumi/")
For Test purposes, in case you'd like to see the output sample. I'll remove it though, thanks.

2022-10-11 19:42 UTC, omobolaji-codes commented on src/utils/autolysis.py
> +    return str(json.loads(resp)["id"])
Got it.

2022-10-11 20:50 UTC, omobolaji-codes commented on src/glovo_scraper.py
> +    script_content = str(soup.find("body").find_all("script")[1].string)  # type: ignore
The line throws this error on mypy check:
`Item "NavigableString" of "Union[Tag, NavigableString, None]" has no attribute "find_all"`
`Item "None" of "Union[Tag, NavigableString, None]" has no attribute "find_all"`

2022-10-11 21:17 UTC, SarthakC commented on src/glovo_scraper.py
> +    script_content = str(soup.find("body").find_all("script")[1].string)  # type: ignore
```suggestion
    script_content = str(soup.find("body").find_all("script")[1].string)  # type: ignore
    
    body_soup = soup.find("body")
    if body_soup is None:
        raise ValueError("The page does not have a body")
    if isinstance(body_soup, NavigableString):
        script_content = str(body_soup.find("script"))
    if isinstance(body_soup, Tag):
        script_content = str(body_soup.find_all("script")[1].string)
```

2022-10-13 10:42 UTC, SarthakC commented
The PR is failing checks.

2022-10-13 13:45 UTC, omobolaji-codes commented
> The PR is failing checks.

2022-10-13 18:36 UTC, SarthakC submitted a review, later dismissed

2022-10-14 07:50 UTC, SarthakC commented on app.py
> +DEBUG = bool(os.getenv("DEBUG"))
https://flask.palletsprojects.com/en/2.2.x/config/

Please read the `DEBUG` section here.

2022-10-14 08:00 UTC, SarthakC requested changes
We can auto-enable debugging

2022-10-18 18:33 UTC, SarthakC approved these changes

2022-10-18 18:44 UTC, merged